### ISSUE TITLE
Add Cueme Underwear device support

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#432]
See buttplugio/stpihkal#22

**Comment by blackspherefollower** [comment]
This might be trickier than it seems.
Because only 1 vibe gets to run at a time, it doesn't quite fit the model that the control schema assumes.

Controlling the first vibe only would make an easy mapping, but kinda misses the point.

The app has support for cycling through the vibes with a couple of different patterns, so maybe this should be implemented as a single vibe device, using a timer to alternate the active vibe?

**Comment by qdot** [comment]
I'm not quite sure what you mean by "only 1 vibe gets to run at a time". Are the vibrators individually addressable? If you turn one on, does another one that's already running turn off?

**Comment by qdot** [comment]
Wow, huh, I guess they did that to keep the battery small or something. That's definitely gonna be interesting, but we can probably just pick a motor or something for the moment for SingleMotorVibrateCmd, and only accept the first command on VibrateCmd or something. Do we have any identifier for product type (boxers/panties/bra)?

**Comment by blackspherefollower** [comment]
Yep, the type is the number on the BLE name.

**Comment by hiss-remi** [comment]
The pictures I've seen make it look like the women's underwear only has four motors, is that correct?

**Comment by blackspherefollower** [comment]
Yep, the woman's underwear had 4 motors.
The men's and bra have 8.
