### ISSUE TITLE
[suggestion] ContractCmd for Lovense Max/Max2

### ISSUE THREAD

**Issue by blue-84** [buttplugio/buttplug-csharp#659]
Hi,

First of all thank you very much for this great library.

I've just made some changes in the core library for supporting the contractions of Lovense Max/Max2 and implemented it in the LovenseProtocol.
I've added the diff at the end for the case you want to merge it to your project.
It's based on git version with tag 0.5.6

[buttplug-csharp-0.5.6-with-maxsupport.diff.txt](https://github.com/buttplugio/buttplug-csharp/files/4251681/buttplug-csharp-0.5.6-with-maxsupport.diff.txt)

**Comment by blue-84** [comment]
Seems that max/max2 just supports contraction level 0..3 instead of 0..5. Have changed my diff.

[buttplug-csharp-0.5.6-with-maxsupport.diff.txt](https://github.com/buttplugio/buttplug-csharp/files/4252339/buttplug-csharp-0.5.6-with-maxsupport.diff.txt)

**Comment by qdot** [comment]
Thanks! 

Unfortunately accepting new messages is a little more complicated than just adding the messages to a single implementation, because we have to consider how to add it to all of our implementations, how each generic message will affect the ~140 pieces of hardware we currently support, how it will serialize (this patch doesn't cover JSON serialization of the message, so it will fail in remote instances), etc...

We have been looking at ways to support inflation in the Max/Max2, and hopefully that'll be coming in within the next couple of months. I've gone ahead and filed https://github.com/buttplugio/buttplug/issues/109 for planning that.
